name: Publish

on:
  workflow_call:
    secrets:
      npmAuthToken:
        required: true

jobs:
  run:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install
        run: yarn install

      - name: Npm Publish
        run: |
          yarn version apply --all
          yarn workspaces changed foreach --worktree --verbose --topological --no-private npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.npmAuthToken }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default_author: github_actions
          message: 'chore(common): publish'
          add: '["*.lock", "*.json", "*.yml"]'
